### ISSUE TITLE
2.7.0 and 2.7.1 --opencl-platform=x --opencl-devices=0 always selects Intel

### ISSUE THREAD

**Issue by yuzi-co** [xmrig/xmrig-amd#132]
On a system with RX580 and Integrated Intel HD 630 on Windows 10
```
--print-platforms
#0: Intel(R) Corporation
#1: Advanced Micro Devices, Inc.
```

When using --opencl-devices=0 always selects first platform (Intel) and fails to compile
Doesn't matter if --opencl-platform set to 1 or 0, same behavior

```
[2018-06-18 20:13:26] #0, GPU #0 Intel(R) HD Graphics 630, intensity: 864 (8/256), cu: 24
[2018-06-18 20:13:26] GPU #0 compiling...
[2018-06-18 20:13:26] Error CL_BUILD_PROGRAM_FAILURE when calling clBuildProgram.
Build log:
1:35:14: error: overloaded function 'amd_bitalign' must have the 'overloadable' attribute
inline uint2 amd_bitalign( const uint2 src0, const uint2 src1, const uint src2)
             ^
opencl-c-common.h:12448:15: note: previous overload of function is here
uint16 __ovld amd_bitalign(uint16 a, uint16 b, uint16 c);
              ^
1:62:12: error: redeclaration of 'amd_bfe' must have the 'overloadable' attribute
inline int amd_bfe(const uint src0, const uint offset, const uint width)
           ^
opencl-c-common.h:12518:13: note: previous overload of function is here
uint __ovld amd_bfe(uint src0, uint src1, uint src2);
            ^
1:62:12: error: conflicting types for 'amd_bfe'
inline int amd_bfe(const uint src0, const uint offset, const uint width)
           ^
opencl-c-common.h:12518:13: note: previous declaration is here
uint __ovld amd_bfe(uint src0, uint src1, uint src2);
            ^

[2018-06-18 20:13:26] Error CL_INVALID_KERNEL_NAME when calling clCreateKernel for kernel cn0.
[2018-06-18 20:13:26] Failed to start threads
```

full command line tested:
xmrig-amd.exe -o stratum+tcp://mine.aeon-pool.com:5555 -u xxxWALLETxxx -p x --opencl-platform=1 --opencl-devices=0 --opencl-launch=864x8 -a cryptonight-lite --variant 1

Fails also for any other algo/variants

**Comment by xmrig** [comment]
@yuzi-co I fixed it, option `--opencl-platform` was broken, about HD 630 it strange, miners works on HD 530 and Iris 640 without issues.
@emailyc command line options is just another syntax for config options, try use https://config.xmrig.com/amd
Thank you.

**Comment by yuzi-co** [comment]
@xmrig 
would be great if automatic intensity settings would also be configured when setting devices (https://github.com/xmrig/xmrig-amd/issues/109)

**Comment by StarLordRammi** [comment]
how do i apply this change? downloading the latest version didnt fix it

**Comment by UselessGuru** [comment]
> I fixed it, option --opencl-platform was broken

Where can I find the fixed version?

**Comment by xmrig** [comment]
Fixed in v2.7.2-beta.
