### ISSUE TITLE
Upgrade from 2.7.3 to 2.8.x failed running: compiling... LLVM ERROR: Cannot select

### ISSUE THREAD

**Issue by shamashii** [xmrig/xmrig-amd#168]
2008R2, download built bins from release, **worked on 2.7.3** but not 2.8.x, any clue?

```
 * ABOUT        XMRig-AMD/2.8.0-rc MSVC/2017
 * LIBS         libuv/1.23.1 OpenCL/2.0 OpenSSL/1.1.1 microhttpd/0.9.59
 * CPU          AMD Athlon(tm) II X2 250 Processor x64 -AES
 * ALGO         cryptonight, donate=5%
 * POOL #1      pool.supportxmr.com:5555 variant auto
 * COMMANDS     hashrate, pause, resume
[2018-10-12 14:19:52] compiling code and initializing GPUs. This will take a whi
le...
[2018-10-12 14:19:52] found AMD platform index: 0, name: Advanced Micro Devices,
 Inc.
[2018-10-12 14:19:52] found OpenCL GPU: Capeverde, cu: 8
[2018-10-12 14:19:52] #0, GPU #0 AMD Radeon HD 7700 Series, intensity: 128 (8/25
6), unroll: 8, cu: 8
[2018-10-12 14:19:53] GPU #0 compiling...
LLVM ERROR: Cannot select: 0x6aec290: i32 = setcc 0x4f3a870, 0x6ad0bd0, 0x6aeba8
0 [ORD=3797] [ID=250]
  0x4f3a870: i64 = add 0x6ad0bd0, 0x6ad9c60 [ORD=3791] [ID=247]
    0x6ad0bd0: i64 = add 0x4f3aa70, 0x6b37c40 [ORD=3790] [ID=244]
      0x4f3aa70: i64 = mul 0x533d560, 0x6ad8350 [ORD=3789] [ID=240]
        0x533d560: i64 = zero_extend 0x6ae20f0 [ORD=3786] [ID=234]
          0x6ae20f0: i32 = add 0x6ae8450, 0x6ade3b0 [ORD=3781] [ID=229]
            0x6ae8450: i32 = AMDILISD::VEXTRACT 0x6adb380, 0x6b3c390 [ORD=3780]
[ID=226]
              0x6adb380: v2i32 = AMDILISD::BITCONV 0x4f1e4b0 [ORD=3779] [ID=222]

                0x4f1e4b0: i64 = add 0x53416a0, 0x5339f20 [ORD=3778] [ID=218]
                  0x53416a0: i64 = add 0x6ad4110, 0x6b2bb80 [ORD=3777] [ID=212]


                  0x5339f20: i64 = zero_extend 0x6adebb0 [ORD=3773] [ID=205]

              0x6b3c390: i32 = TargetConstant<2> [ORD=4080] [ID=91]
            0x6ade3b0: i32,ch = CopyFromReg 0x4ef6ab0, 0x5346df0 [ORD=3781] [ID=
108]
              0x5346df0: i32 = Register %vreg51 [ORD=3781] [ID=10]
        0x6ad8350: i64 = zero_extend 0x6ad7740 [ORD=3788] [ID=163]
          0x6ad7740: i32 = AMDILISD::VEXTRACT 0x4f28450, 0x6b3c390 [ORD=3787] [I
D=154]
            0x4f28450: v2i32 = AMDILISD::BITCONV 0x6ad9c60 [ORD=3782] [ID=132]
              0x6ad9c60: i64,ch = CopyFromReg 0x4ef6ab0, 0x6add2a0 [ORD=3782] [I
D=109]
                0x6add2a0: i64 = Register %vreg43 [ORD=3782] [ID=11]
            0x6b3c390: i32 = TargetConstant<2> [ORD=4080] [ID=91]
      0x6b37c40: i64 = zero_extend 0x6b39260 [ORD=3785] [ID=241]
        0x6b39260: i32,ch = llvm.AMDIL.mulhi.u32 0x4ef6ab0, 0x6ad3f10, 0x4e4ed60
, 0x6ae20f0 [ORD=3784] [ID=235]
          0x6ad3f10: i32 = TargetConstant<2716> [ORD=3772] [ID=6]
          0x4e4ed60: i32 = AMDILISD::VEXTRACT 0x4f28450, 0x6ae3500 [ORD=3783] [I
D=153]
            0x4f28450: v2i32 = AMDILISD::BITCONV 0x6ad9c60 [ORD=3782] [ID=132]
              0x6ad9c60: i64,ch = CopyFromReg 0x4ef6ab0, 0x6add2a0 [ORD=3782] [I
D=109]
                0x6add2a0: i64 = Register %vreg43 [ORD=3782] [ID=11]
            0x6ae3500: i32 = TargetConstant<1> [ORD=4079] [ID=89]
          0x6ae20f0: i32 = add 0x6ae8450, 0x6ade3b0 [ORD=3781] [ID=229]
            0x6ae8450: i32 = AMDILISD::VEXTRACT 0x6adb380, 0x6b3c390 [ORD=3780]
[ID=226]
              0x6adb380: v2i32 = AMDILISD::BITCONV 0x4f1e4b0 [ORD=3779] [ID=222]

                0x4f1e4b0: i64 = add 0x53416a0, 0x5339f20 [ORD=3778] [ID=218]
                  0x53416a0: i64 = add 0x6ad4110, 0x6b2bb80 [ORD=3777] [ID=212]


                  0x5339f20: i64 = zero_extend 0x6adebb0 [ORD=3773] [ID=205]

              0x6b3c390: i32 = TargetConstant<2> [ORD=4080] [ID=91]
            0x6ade3b0: i32,ch = CopyFromReg 0x4ef6ab0, 0x5346df0 [ORD=3781] [ID=
108]
              0x5346df0: i32 = Register %vreg51 [ORD=3781] [ID=10]
    0x6ad9c60: i64,ch = CopyFromReg 0x4ef6ab0, 0x6add2a0 [ORD=3782] [ID=109]
      0x6add2a0: i64 = Register %vreg43 [ORD=3782] [ID=11]
  0x6ad0bd0: i64 = add 0x4f3aa70, 0x6b37c40 [ORD=3790] [ID=244]
    0x4f3aa70: i64 = mul 0x533d560, 0x6ad8350 [ORD=3789] [ID=240]
      0x533d560: i64 = zero_extend 0x6ae20f0 [ORD=3786] [ID=234]
        0x6ae20f0: i32 = add 0x6ae8450, 0x6ade3b0 [ORD=3781] [ID=229]
          0x6ae8450: i32 = AMDILISD::VEXTRACT 0x6adb380, 0x6b3c390 [ORD=3780] [I
D=226]
            0x6adb380: v2i32 = AMDILISD::BITCONV 0x4f1e4b0 [ORD=3779] [ID=222]
              0x4f1e4b0: i64 = add 0x53416a0, 0x5339f20 [ORD=3778] [ID=218]
                0x53416a0: i64 = add 0x6ad4110, 0x6b2bb80 [ORD=3777] [ID=212]
                  0x6ad4110: i64 = mul 0x6ad7440, 0x6ad7340 [ORD=3776] [ID=206]


                  0x6b2bb80: i64 = AMDILISD::LCREATE 0x6aed9a0, 0x6ae9960 [ORD=3
769] [ID=181]


                0x5339f20: i64 = zero_extend 0x6adebb0 [ORD=3773] [ID=205]
                  0x6adebb0: i32,ch = llvm.AMDIL.mulhi.u32 0x4ef6ab0, 0x6ad3f10,
 0x6ad19e0, 0x6ad8a50 [ORD=3772] [ID=198]



            0x6b3c390: i32 = TargetConstant<2> [ORD=4080] [ID=91]
          0x6ade3b0: i32,ch = CopyFromReg 0x4ef6ab0, 0x5346df0 [ORD=3781] [ID=10
8]
            0x5346df0: i32 = Register %vreg51 [ORD=3781] [ID=10]
      0x6ad8350: i64 = zero_extend 0x6ad7740 [ORD=3788] [ID=163]
        0x6ad7740: i32 = AMDILISD::VEXTRACT 0x4f28450, 0x6b3c390 [ORD=3787] [ID=
154]
          0x4f28450: v2i32 = AMDILISD::BITCONV 0x6ad9c60 [ORD=3782] [ID=132]
            0x6ad9c60: i64,ch = CopyFromReg 0x4ef6ab0, 0x6add2a0 [ORD=3782] [ID=
109]
              0x6add2a0: i64 = Register %vreg43 [ORD=3782] [ID=11]
          0x6b3c390: i32 = TargetConstant<2> [ORD=4080] [ID=91]
    0x6b37c40: i64 = zero_extend 0x6b39260 [ORD=3785] [ID=241]
      0x6b39260: i32,ch = llvm.AMDIL.mulhi.u32 0x4ef6ab0, 0x6ad3f10, 0x4e4ed60,
0x6ae20f0 [ORD=3784] [ID=235]
        0x6ad3f10: i32 = TargetConstant<2716> [ORD=3772] [ID=6]
        0x4e4ed60: i32 = AMDILISD::VEXTRACT 0x4f28450, 0x6ae3500 [ORD=3783] [ID=
153]
          0x4f28450: v2i32 = AMDILISD::BITCONV 0x6ad9c60 [ORD=3782] [ID=132]
            0x6ad9c60: i64,ch = CopyFromReg 0x4ef6ab0, 0x6add2a0 [ORD=3782] [ID=
109]
              0x6add2a0: i64 = Register %vreg43 [ORD=3782] [ID=11]
          0x6ae3500: i32 = TargetConstant<1> [ORD=4079] [ID=89]
        0x6ae20f0: i32 = add 0x6ae8450, 0x6ade3b0 [ORD=3781] [ID=229]
          0x6ae8450: i32 = AMDILISD::VEXTRACT 0x6adb380, 0x6b3c390 [ORD=3780] [I
D=226]
            0x6adb380: v2i32 = AMDILISD::BITCONV 0x4f1e4b0 [ORD=3779] [ID=222]
              0x4f1e4b0: i64 = add 0x53416a0, 0x5339f20 [ORD=3778] [ID=218]
                0x53416a0: i64 = add 0x6ad4110, 0x6b2bb80 [ORD=3777] [ID=212]
                  0x6ad4110: i64 = mul 0x6ad7440, 0x6ad7340 [ORD=3776] [ID=206]


                  0x6b2bb80: i64 = AMDILISD::LCREATE 0x6aed9a0, 0x6ae9960 [ORD=3
769] [ID=181]


                0x5339f20: i64 = zero_extend 0x6adebb0 [ORD=3773] [ID=205]
                  0x6adebb0: i32,ch = llvm.AMDIL.mulhi.u32 0x4ef6ab0, 0x6ad3f10,
 0x6ad19e0, 0x6ad8a50 [ORD=3772] [ID=198]



            0x6b3c390: i32 = TargetConstant<2> [ORD=4080] [ID=91]
          0x6ade3b0: i32,ch = CopyFromReg 0x4ef6ab0, 0x5346df0 [ORD=3781] [ID=10
8]
            0x5346df0: i32 = Register %vreg51 [ORD=3781] [ID=10]

```

**Comment by xmrig** [comment]
To be clear v2.7.3 with disabled opencl cache `"cache": false,` works on same machine/OS and driver version, but 2.8 not?
Thank you.

**Comment by shamashii** [comment]
> To be clear v2.7.3 with disabled opencl cache `"cache": false,` works on same machine/OS and driver version, but 2.8 not?
> Thank you.

Yes, both version has been set "cache": false in config.json, and v2.7.3 worked, 2.8 crashed.

**Comment by xmronadaily** [comment]
Having the same issue with HD 6990 gpus...

 * ABOUT        XMRig-AMD/2.8.1 MSVC/2017
 * LIBS         libuv/1.23.1 OpenCL/2.0 OpenSSL/1.1.1 microhttpd/0.9.59
 * CPU          AMD Athlon(tm) II X2 250 Processor x64 -AES
 * ALGO         cryptonight, donate=5%
 * POOL #1      donate.v2.xmrig.com:3333 variant auto
 * COMMANDS     hashrate, pause, resume
[2018-10-13 18:47:55] compiling code and initializing GPUs. This will take a while...
[2018-10-13 18:47:57] found AMD platform index: 0, name: Advanced Micro Devices, Inc.
[2018-10-13 18:47:57] found OpenCL GPU: Cayman, cu: 24
[2018-10-13 18:47:57] found OpenCL GPU: Cayman, cu: 24
[2018-10-13 18:47:57] found OpenCL GPU: Cayman, cu: 24
[2018-10-13 18:47:57] found OpenCL GPU: Cayman, cu: 24
[2018-10-13 18:47:57] found OpenCL GPU: Tahiti, cu: 32
[2018-10-13 18:47:57] found OpenCL GPU: Pitcairn, cu: 16
[2018-10-13 18:47:57] #0, GPU #0 AMD Radeon HD 6900 Series, intensity: 768 (8/256), unroll: 8, cu: 24
[2018-10-13 18:47:57] GPU #0 compiling...
LLVM ERROR: Cannot select: 0x215cc9fb850: i32 = setcc 0x215cadf84c0, 0x215cadfdd10, 0x215ccbfa180 [ORD=3789] [ID=253]
  0x215cadf84c0: i64 = add 0x215cadfdd10, 0x215ccc16840 [ORD=3783] [ID=249]
    0x215cadfdd10: i64 = add 0x215cbc83e20, 0x215ccc11df0 [ORD=3782] [ID=246]
      0x215cbc83e20: i64 = mul 0x215ccc15e30, 0x215cadf0b40 [ORD=3781] [ID=242]
        0x215ccc15e30: i64 = zero_extend 0x215cadf0540 [ORD=3778] [ID=236]
          0x215cadf0540: i32 = add 0x215cadf1950, 0x215ccc14820 [ORD=3773] [ID=231]
            0x215cadf1950: i32 = AMDILISD::VEXTRACT 0x215ccc05230, 0x215ccbffad0 [ORD=3772] [ID=227]
              0x215ccc05230: v2i32 = AMDILISD::BITCONV 0x215cadf89c0 [ORD=3771] [ID=223]
                0x215cadf89c0: i64 = add 0x215ccc11ff0, 0x215ccc12700 [ORD=3770] [ID=219]
                  0x215ccc11ff0: i64 = add 0x215ccc15330, 0x215cbdaf790 [ORD=3769] [ID=213]


                  0x215ccc12700: i64 = zero_extend 0x215ccc0a380 [ORD=3765] [ID=205]

              0x215ccbffad0: i32 = TargetConstant<2> [ORD=4072] [ID=91]
            0x215ccc14820: i32,ch = CopyFromReg 0x215c8ce8240, 0x215cadfa8e0 [ORD=3773] [ID=108]
              0x215cadfa8e0: i32 = Register %vreg49 [ORD=3773] [ID=10]
        0x215cadf0b40: i64 = zero_extend 0x215ccc09c70 [ORD=3780] [ID=163]
          0x215ccc09c70: i32 = AMDILISD::VEXTRACT 0x215ccc15f30, 0x215ccbffad0 [ORD=3779] [ID=154]
            0x215ccc15f30: v2i32 = AMDILISD::BITCONV 0x215ccc16840 [ORD=3774] [ID=132]
              0x215ccc16840: i64,ch = CopyFromReg 0x215c8ce8240, 0x215ccc15430 [ORD=3774] [ID=109]
                0x215ccc15430: i64 = Register %vreg41 [ORD=3774] [ID=11]
            0x215ccbffad0: i32 = TargetConstant<2> [ORD=4072] [ID=91]
      0x215ccc11df0: i64 = zero_extend 0x215cadf1150 [ORD=3777] [ID=243]
        0x215cadf1150: i32 = llvm.AMDIL.mulhi.u32 0x215ccc0e5c0, 0x215ccc14010, 0x215cadf0540 [ORD=3776] [ID=237]
          0x215ccc0e5c0: i32 = TargetConstant<3113> [ORD=3764] [ID=6]
          0x215ccc14010: i32 = AMDILISD::VEXTRACT 0x215ccc15f30, 0x215ccc13710 [ORD=3775] [ID=153]
            0x215ccc15f30: v2i32 = AMDILISD::BITCONV 0x215ccc16840 [ORD=3774] [ID=132]
              0x215ccc16840: i64,ch = CopyFromReg 0x215c8ce8240, 0x215ccc15430 [ORD=3774] [ID=109]
                0x215ccc15430: i64 = Register %vreg41 [ORD=3774] [ID=11]
            0x215ccc13710: i32 = TargetConstant<1> [ORD=4071] [ID=89]
          0x215cadf0540: i32 = add 0x215cadf1950, 0x215ccc14820 [ORD=3773] [ID=231]
            0x215cadf1950: i32 = AMDILISD::VEXTRACT 0x215ccc05230, 0x215ccbffad0 [ORD=3772] [ID=227]
              0x215ccc05230: v2i32 = AMDILISD::BITCONV 0x215cadf89c0 [ORD=3771] [ID=223]
                0x215cadf89c0: i64 = add 0x215ccc11ff0, 0x215ccc12700 [ORD=3770] [ID=219]
                  0x215ccc11ff0: i64 = add 0x215ccc15330, 0x215cbdaf790 [ORD=3769] [ID=213]


                  0x215ccc12700: i64 = zero_extend 0x215ccc0a380 [ORD=3765] [ID=205]

              0x215ccbffad0: i32 = TargetConstant<2> [ORD=4072] [ID=91]
            0x215ccc14820: i32,ch = CopyFromReg 0x215c8ce8240, 0x215cadfa8e0 [ORD=3773] [ID=108]
              0x215cadfa8e0: i32 = Register %vreg49 [ORD=3773] [ID=10]
    0x215ccc16840: i64,ch = CopyFromReg 0x215c8ce8240, 0x215ccc15430 [ORD=3774] [ID=109]
      0x215ccc15430: i64 = Register %vreg41 [ORD=3774] [ID=11]
  0x215cadfdd10: i64 = add 0x215cbc83e20, 0x215ccc11df0 [ORD=3782] [ID=246]
    0x215cbc83e20: i64 = mul 0x215ccc15e30, 0x215cadf0b40 [ORD=3781] [ID=242]
      0x215ccc15e30: i64 = zero_extend 0x215cadf0540 [ORD=3778] [ID=236]
        0x215cadf0540: i32 = add 0x215cadf1950, 0x215ccc14820 [ORD=3773] [ID=231]
          0x215cadf1950: i32 = AMDILISD::VEXTRACT 0x215ccc05230, 0x215ccbffad0 [ORD=3772] [ID=227]
            0x215ccc05230: v2i32 = AMDILISD::BITCONV 0x215cadf89c0 [ORD=3771] [ID=223]
              0x215cadf89c0: i64 = add 0x215ccc11ff0, 0x215ccc12700 [ORD=3770] [ID=219]
                0x215ccc11ff0: i64 = add 0x215ccc15330, 0x215cbdaf790 [ORD=3769] [ID=213]
                  0x215ccc15330: i64 = mul 0x215ccc0aa80, 0x215ccc10ae0 [ORD=3768] [ID=206]


                  0x215cbdaf790: i64 = AMDILISD::LCREATE 0x215cbdaf190, 0x215ccc008e0 [ORD=3761] [ID=181]


                0x215ccc12700: i64 = zero_extend 0x215ccc0a380 [ORD=3765] [ID=205]
                  0x215ccc0a380: i32 = llvm.AMDIL.mulhi.u32 0x215ccc0e5c0, 0x215cadf0140, 0x215ccc14620 [ORD=3764] [ID=198]



            0x215ccbffad0: i32 = TargetConstant<2> [ORD=4072] [ID=91]
          0x215ccc14820: i32,ch = CopyFromReg 0x215c8ce8240, 0x215cadfa8e0 [ORD=3773] [ID=108]
            0x215cadfa8e0: i32 = Register %vreg49 [ORD=3773] [ID=10]
      0x215cadf0b40: i64 = zero_extend 0x215ccc09c70 [ORD=3780] [ID=163]
        0x215ccc09c70: i32 = AMDILISD::VEXTRACT 0x215ccc15f30, 0x215ccbffad0 [ORD=3779] [ID=154]
          0x215ccc15f30: v2i32 = AMDILISD::BITCONV 0x215ccc16840 [ORD=3774] [ID=132]
            0x215ccc16840: i64,ch = CopyFromReg 0x215c8ce8240, 0x215ccc15430 [ORD=3774] [ID=109]
              0x215ccc15430: i64 = Register %vreg41 [ORD=3774] [ID=11]
          0x215ccbffad0: i32 = TargetConstant<2> [ORD=4072] [ID=91]
    0x215ccc11df0: i64 = zero_extend 0x215cadf1150 [ORD=3777] [ID=243]
      0x215cadf1150: i32 = llvm.AMDIL.mulhi.u32 0x215ccc0e5c0, 0x215ccc14010, 0x215cadf0540 [ORD=3776] [ID=237]
        0x215ccc0e5c0: i32 = TargetConstant<3113> [ORD=3764] [ID=6]
        0x215ccc14010: i32 = AMDILISD::VEXTRACT 0x215ccc15f30, 0x215ccc13710 [ORD=3775] [ID=153]
          0x215ccc15f30: v2i32 = AMDILISD::BITCONV 0x215ccc16840 [ORD=3774] [ID=132]
            0x215ccc16840: i64,ch = CopyFromReg 0x215c8ce8240, 0x215ccc15430 [ORD=3774] [ID=109]
              0x215ccc15430: i64 = Register %vreg41 [ORD=3774] [ID=11]
          0x215ccc13710: i32 = TargetConstant<1> [ORD=4071] [ID=89]
        0x215cadf0540: i32 = add 0x215cadf1950, 0x215ccc14820 [ORD=3773] [ID=231]
          0x215cadf1950: i32 = AMDILISD::VEXTRACT 0x215ccc05230, 0x215ccbffad0 [ORD=3772] [ID=227]
            0x215ccc05230: v2i32 = AMDILISD::BITCONV 0x215cadf89c0 [ORD=3771] [ID=223]
              0x215cadf89c0: i64 = add 0x215ccc11ff0, 0x215ccc12700 [ORD=3770] [ID=219]
                0x215ccc11ff0: i64 = add 0x215ccc15330, 0x215cbdaf790 [ORD=3769] [ID=213]
                  0x215ccc15330: i64 = mul 0x215ccc0aa80, 0x215ccc10ae0 [ORD=3768] [ID=206]


                  0x215cbdaf790: i64 = AMDILISD::LCREATE 0x215cbdaf190, 0x215ccc008e0 [ORD=3761] [ID=181]


                0x215ccc12700: i64 = zero_extend 0x215ccc0a380 [ORD=3765] [ID=205]
                  0x215ccc0a380: i32 = llvm.AMDIL.mulhi.u32 0x215ccc0e5c0, 0x215cadf0140, 0x215ccc14620 [ORD=3764] [ID=198]



            0x215ccbffad0: i32 = TargetConstant<2> [ORD=4072] [ID=91]
          0x215ccc14820: i32,ch = CopyFromReg 0x215c8ce8240, 0x215cadfa8e0 [ORD=3773] [ID=108]
            0x215cadfa8e0: i32 = Register %vreg49 [ORD=3773] [ID=10]
In function: __OpenCL_cn1_v2_monero_kernel
Press any key to continue . . .

**Comment by shamashii** [comment]
Have found some alternative drivers on vendor site, not on AMD, finally make it run again.

**Comment by xmrig** [comment]
Fixed in v2.8.2.

**Comment by jnnccc** [comment]
the problem still exist on hd690
 * ABOUT        XMRig-AMD/2.8.2 gcc/5.4.1
 * LIBS         libuv/1.22.1-dev OpenCL/2.0 OpenSSL/1.0.1 
 * CPU          Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz x64 -AES
 * ALGO         cryptonight, donate=5%
 * POOL #1      localhost:7003 variant 2
 * COMMANDS     hashrate, pause, resume
[2018-10-19 02:50:02] compiling code and initializing GPUs. This will take a while...
[2018-10-19 02:50:02] found AMD platform index: 0, name: Advanced Micro Devices, Inc.
[2018-10-19 02:50:02] found OpenCL GPU: Cypress, cu: 20
[2018-10-19 02:50:02] found OpenCL GPU: Cypress, cu: 20
[2018-10-19 02:50:02] #0, GPU #0 ATI Radeon HD 5900 Series, intensity: 320 (8/256), unroll: 8, cu: 20
[2018-10-19 02:50:02] GPU #0 compiling...
LLVM ERROR: Cannot select: 0x2c0d8f0: i32 = setcc 0x23c7130, 0x2719f80, 0x2c0d4e0 [ID=248]
  0x23c7130: i64 = AMDILISD::ADD 0x2719f80, 0x22f7d00 [ID=246]
    0x2719f80: i64 = AMDILISD::ADD 0x22c1fe0, 0x202d270 [ORD=3763] [ID=243]
      0x22c1fe0: i64 = mul 0x234c2d0, 0x288ffb0 [ORD=3762] [ID=240]
        0x234c2d0: i64 = zero_extend 0x2be1220 [ORD=3759] [ID=234]
          0x2be1220: i32 = AMDILISD::ADD 0x2719d80, 0x1b5da30 [ORD=3754] [ID=228]
            0x2719d80: i32 = AMDILISD::VEXTRACT 0x2beb820, 0x23c4e10 [ORD=3753] [ID=225]
              0x2beb820: v2i32 = AMDILISD::BITCONV 0x2009cd0 [ORD=3752] [ID=221]
                0x2009cd0: i64 = AMDILISD::ADD 0x1eb2c90, 0x1b80be0 [ORD=3751] [ID=217]
                  0x1eb2c90: i64 = AMDILISD::ADD 0x2bec630, 0x21ed840 [ORD=3750] [ID=211]

**Comment by jnnccc** [comment]
the problem still exist on hd5970

ABOUT XMRig-AMD/2.8.2 gcc/5.4.1
LIBS libuv/1.22.1-dev OpenCL/2.0 OpenSSL/1.0.1
CPU Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz x64 -AES
ALGO cryptonight, donate=5%
POOL #1 localhost:7003 variant 2
COMMANDS hashrate, pause, resume
[2018-10-19 02:50:02] compiling code and initializing GPUs. This will take a while...
[2018-10-19 02:50:02] found AMD platform index: 0, name: Advanced Micro Devices, Inc.
[2018-10-19 02:50:02] found OpenCL GPU: Cypress, cu: 20
[2018-10-19 02:50:02] found OpenCL GPU: Cypress, cu: 20
[2018-10-19 02:50:02] #0, GPU #0 ATI Radeon HD 5900 Series, intensity: 320 (8/256), unroll: 8, cu: 20
[2018-10-19 02:50:02] GPU #0 compiling...
LLVM ERROR: Cannot select: 0x2c0d8f0: i32 = setcc 0x23c7130, 0x2719f80, 0x2c0d4e0 [ID=248]
0x23c7130: i64 = AMDILISD::ADD 0x2719f80, 0x22f7d00 [ID=246]
0x2719f80: i64 = AMDILISD::ADD 0x22c1fe0, 0x202d270 [ORD=3763] [ID=243]
0x22c1fe0: i64 = mul 0x234c2d0, 0x288ffb0 [ORD=3762] [ID=240]
0x234c2d0: i64 = zero_extend 0x2be1220 [ORD=3759] [ID=234]
0x2be1220: i32 = AMDILISD::ADD 0x2719d80, 0x1b5da30 [ORD=3754] [ID=228]
0x2719d80: i32 = AMDILISD::VEXTRACT 0x2beb820, 0x23c4e10 [ORD=3753] [ID=225]
0x2beb820: v2i32 = AMDILISD::BITCONV 0x2009cd0 [ORD=3752] [ID=221]
0x2009cd0: i64 = AMDILISD::ADD 0x1eb2c90, 0x1b80be0 [ORD=3751] [ID=217]
0x1eb2c90: i64 = AMDILISD::ADD 0x2bec630, 0x21ed840 [ORD=3750] [ID=211]

**Comment by jnnccc** [comment]
> Have found some alternative drivers on vendor site, not on AMD, finally make it run again.
cite the link please
