### ISSUE TITLE
Can't build under mac os x 

### ISSUE THREAD

**Issue by cl4r0s** [xmrig/xmrig-amd#223]
during make in MacOs 10.13.6
I got these errors: 
[ 83%] Building CXX object CMakeFiles/xmrig-amd.dir/src/crypto/CryptoNight.cpp.o
/Users/cl4r0s/build/xmrig-amd/src/crypto/CryptoNight.cpp:312:13: warning: unused variable 'info' [-Wunused-variable]
    MemInfo info = Mem::create(&m_ctx, m_algorithm, 1);
            ^
1 warning generated.
[ 85%] Building CXX object CMakeFiles/xmrig-amd.dir/src/crypto/CryptonightR_gen.cpp.o
In file included from /Users/cl4r0s/build/xmrig-amd/src/crypto/CryptonightR_gen.cpp:27:
In file included from /Users/cl4r0s/build/xmrig-amd/src/crypto/CryptoNight_monero.h:155:
/Users/cl4r0s/build/xmrig-amd/src/crypto/variant4_random_math.h:182:12: warning: unused function 'v4_random_math_init'
      [-Wunused-function]
static int v4_random_math_init(struct V4_Instruction* code, const uint64_t height)
           ^
1 warning generated.
[ 86%] Building CXX object CMakeFiles/xmrig-amd.dir/src/common/log/SysLog.cpp.o

The build then completes:
$ ./xmrig-amd -V
XMRig-AMD 2.12.0
 built on Feb 18 2019 with clang 10.0.0 (clang-1000.10.44.4)
 features: 64-bit AES
libuv/1.26.0
microhttpd/0.9.62
OpenSSL/1.0.2q
./xmrig-amd --print-platforms
#0: Apple

But running ./xmrig-amd gives this error: 
"cryptonight" hash self-test failed.
Removing the self tests with return = true doesn't help as the program ends with a segmentation fault

**Comment by xmrig** [comment]
This issue should be fixed in [dev](https://github.com/xmrig/xmrig-amd/commits/dev) branch. Another option is build miner without `cn/gpu` support: `-DWITH_CN_GPU=OFF`. Related issue: https://github.com/xmrig/xmrig/issues/925
Thank you.

**Comment by cl4r0s** [comment]
First of all, thank you for your very very fast answer.
I just cloned and compiled the dev branch
During the compilation I still have a warning:
[ 86%] Building CXX object CMakeFiles/xmrig-amd-notls.dir/src/crypto/CryptoNight.cpp.o
../build/xmrig-amd/src/crypto/CryptoNight.cpp:322:13: warning: unused variable 'info' [-Wunused-variable]
    MemInfo info = Mem::create(&m_ctx, m_algorithm, 1);
            ^
1 warning generated.

The compilation ends successfully 
./xmrig-amd-notls -V
XMRig-AMD 2.12.1-dev
 built on Feb 19 2019 with clang 10.0.0 (clang-1000.10.44.4)
 features: 64-bit AES
libuv/1.26.0
microhttpd/0.9.62

But the program doesn't work:
 * ABOUT        XMRig-AMD/2.12.1-dev clang/10.0.0
 * LIBS         libuv/1.26.0 OpenCL/1.2 OpenSSL/1.0.2q microhttpd/0.9.62 
 * CPU                 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz x64 AES
 * ALGO         cryptonight, donate=1%
 * POOL #1      msr.go-mine.it:3333 variant msr
 * API BIND     0.0.0.0:8080
 * COMMANDS     hashrate, pause, resume
[2019-02-19 11:49:24] compiling code and initializing GPUs. This will take a while...
[2019-02-19 11:49:24] #00, GPU #00 ATI Radeon HD 6750M, i:120 (6/256), si:1/2, u:8, cu:6
[2019-02-19 11:49:24]              0.23/0.12/0 GB
[2019-02-19 11:49:24] GPU #0 compiling...
[2019-02-19 11:49:24] GPU #0 compilation completed, elapsed time 0.001s
[2019-02-19 11:49:24] Error CL_INVALID_PROGRAM_EXECUTABLE when calling clCreateKernel for kernel cn0.
[2019-02-19 11:49:24] Failed to start threads.

Test both ssl and tls versions of dev branch

At lest for me, the latest version working is v2.9.4

**Comment by cl4r0s** [comment]
Tested on release version 2.13.
Compilation now end without error or warnings!

Anyway, doesn't work anymore on my iMac
iMac:xmrig-amd Claudio$ ./xmrig-amd-notls 
 * ABOUT        XMRig-AMD/2.13.0 clang/10.0.0
 * LIBS         libuv/1.26.0 OpenCL/1.2 microhttpd/0.9.62 
 * CPU                 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz x64 AES
 * ALGO         cryptonight, donate=1%
 * POOL #1      msr.go-mine.it:3333 variant msr
 * COMMANDS     hashrate, pause, resume
[2019-03-04 22:56:22] compiling code and initializing GPUs. This will take a while...
[2019-03-04 22:56:22] #00, GPU #00 ATI Radeon HD 6750M, i:64 (4/256), si:2/2, u:8, cu:6
[2019-03-04 22:56:22]              0.12/0.12/0 GB
[2019-03-04 22:56:22] GPU #0 compiling...
[2019-03-04 22:56:22] GPU #0 compilation completed, elapsed time 0.000s
[2019-03-04 22:56:22] Error CL_INVALID_PROGRAM_EXECUTABLE when calling clCreateKernel for kernel cn0.
[2019-03-04 22:56:22] Failed to start threads.

Without any thread configuration just return this error:
[2019-03-04 23:01:40] compiling code and initializing GPUs. This will take a while...
[2019-03-04 23:01:40] found OpenCL GPU: ATI Radeon HD 6750M, cu: 6
[2019-03-04 23:01:40] Failed to start threads.

Now it's all a matter of cuda compilation, but I'm supposing that old cards like this one are not supported anymore.  If this is a bad hypothesis, please drop an answer here. 

Otherwise it would be nice if someone with a more powerful amd card could test it...

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/releases/tag/v4.0.0-beta
